### ISSUE TITLE
Integrate classifier into hydra

### ISSUE THREAD

**Issue by zeef69** [HLCaptain/ssl-in-the-wild#23]
#11 -es második fele.
Train futtatása classifier-rel Dockerben, tesztelve a megírt `config/` fájlokat.
Eval futtatása Dockerben.

GPU-n való tesztelés

**Kérdések:**
Lehessen külön futattni a VICReg-es trainelést és felhasználói interakcióra lehessen a klasszifikációt elvégezni? Vagy a teljes train-train-test fusson le? (Docker fájlban CMD parancsokra kell cserélni az ENTRYPOINT-ot.)

**Comment by HLCaptain** [comment]
Solved with #27
