### ISSUE TITLE
ValueError: expected 4D input (got 3D input)

### ISSUE THREAD

**Issue by zeef69** [HLCaptain/ssl-in-the-wild#33]
https://github.com/HLCaptain/ssl-in-the-wild/blob/eba06025e72e4178e2c82f5faad9f77d0dad26f1/src/models/classifier_module.py#L71C29-L71C29

Ebben a sorban, ha tömb elemből csak a 0. elemre az SSL nélküli tanításnál akkor hibát ad. Emlékeim szerinte ezt te módosítottad erre, mi volt az oka? Nekem fut átírva az SSL-el tanítás `y_hat = self.forward(x)` -re.
Ha így kell maradnia, akkor egy új Classifier osztályt kell írnom hozzá a backbone-tól függően.

**Comment by HLCaptain** [comment]
Ha fut, akkor szuper, nekem nem futott dockerrel, de ha át kell írni, akkor át kell írni. A probléma oka kérdéses.

**Comment by HLCaptain** [comment]
Arra gondolok, hogy inkonzisztens pip verziók okozhatnak problémákat, viszont az biztos, hogy a mostani megoldás nem crashel el docker-ben.

**Comment by zeef69** [comment]
> Ha fut, akkor szuper, nekem nem futott dockerrel, de ha át kell írni, akkor át kell írni. A probléma oka kérdéses.

Nem dockerben próbáltam, hanem csak simán konzolról.

**Comment by zeef69** [comment]
#47 PR solved this issue
