### ISSUE TITLE
Fix training model

### ISSUE THREAD

**Issue by HLCaptain** [HLCaptain/ssl-in-the-wild#8]
I am getting the error below when trying to run the model:

```
H:\AI\ssl-in-the-wild>python src/train.py trainer=gpu               
In 'hydra/config': Could not find 'hydra/job_logging/colorlog'

Available options in 'hydra/job_logging':
        default
        disabled
        none
        stdout
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file://H:\AI\ssl-in-the-wild\configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Update `README.md` with proper commands to run the training process.

**Comment by zeef69** [comment]
Ez még nem szükséges az MS1-hez. Ott a `README.md` szerint még a notebook-ot lehet futtani.
Mivel a trainer-hez kellene hogy legyen modell az egész mögött, így ez még jó ideig hibát fog adni. Ami aggasztóbb, hogy a logolót még nem módosítottam, így csak a default értékek vannak bent, így ezt a hydra húzza le valahonnan, a `configs\hydra\default.yaml` fájlba, ez okozza a bug-ot.

**Comment by HLCaptain** [comment]
Yes, I see now. In this case, I will assign @czifrushanna to this issue to start implementing training and evaluation of the required models, thus fixing the issue.
